Support parent-child relationship
mongodb-labs/elastic2-doc-manager pull request #25
Opened 2016-11-02 18:11 UTC by ShaneHarvey

This builds on @xiaogaozi's work on #3.

Add support for parent-child mapping.
 

### Example Usage
Let's use the data from the [Elasticsearch Parent-Child Mapping docs](https://www.elastic.co/guide/en/elasticsearch/guide/2.x/parent-child-mapping.html) and adapt it to MongoDB. Suppose you have a `company` database in MongoDB with the collections `branch` and `employees`. Use this script to load some sample data:
**Note**: this example assumes you have a MongoDB replica set on localhost:27017 and an Elasticsearch instance on localhost:9200.
```python
from pymongo import MongoClient

HOST = 'mongodb://localhost:27017'
client = MongoClient(HOST)

company = client.company
branch = company.branch
employee = company.employee

def insert_parent_child(parent_doc, child_doc, parent_field):
    res = branch.insert_one(parent_doc)
    child_doc[parent_field] = res.inserted_id
    employee.insert_one(child_doc)

branch_docs = [
    {'name': 'London Westminster', 'city': 'London', 'country': 'UK'},
    {'name': 'Liverpool Central', 'city': 'Liverpool', 'country': 'UK'},
    {'name': 'Champs Elysees', 'city': 'Paris', 'country': 'France'}]
employee_docs = [
    {'name': 'Mark Thomas', 'dob': '1982-05-16', 'hobby': 'diving'},
    {'name': 'Barry Smith', 'dob': '1979-04-01', 'hobby': 'hiking'},
    {'name': 'Adrien Grand', 'dob': '1987-05-11', 'hobby': 'horses'}]

for branch_doc, employee_doc in zip(branch_docs, employee_docs):
    insert_parent_child(branch_doc, employee_doc, 'branch_id')
```

In the current pull request, the elastic-doc-manager does not automatically create the parent-child mapping. So create the mapping manually before running mongo-connector:
```
curl -XPUT 'http://localhost:9200/company' -d '{
  "mappings": {
    "branch": {},
    "employee": {
      "_parent": {
        "type": "branch" 
      }
    }
  }
}'
```

Next, create the mongo-connector config file with parent-child mapping options:
```json
{
  "mainAddress": "localhost:27017",
  "verbosity": 2,
  "docManagers":[
    {
      "docManager": "elastic2_doc_manager",
      "targetURL": "localhost:9200",
      "args": {
        "routing": {
          "company": {
            "employee": {
              "parentField": "branch_id"
            }
          }
        }
      }
    }
  ]
}
```

Next, run mongo-connector with the above config file:
`mongo-connector -c parent-child-config.json`

Finally, you can query Elasticsearch with your MongoDB data.

Query Elasticsearch for children by their parents:
```
curl -XGET 'http://localhost:9200/company/employee/_search/?pretty=1' -d '{
  "query": {
    "has_parent": {
      "type": "branch",
      "query": {
        "match": {
          "country": "UK"
        }
      }
    }
  }
}'
```

Or, query Elasticsearch for parents by their children:
```
curl -XGET 'http://localhost:9200/company/branch/_search/?pretty=1' -d '{
  "query": {
    "has_child": {
      "type": "employee",
      "query": {
        "range": {
          "dob": {
            "gte": "1980-01-01"
          }
        }
      }
    }
  }
}'
```

### Up for discussion:
- Should the config file format be changed?
- Should the DocManager automatically create the parent and child index/mapping?
  - In this case, we need to add a `parentType` field to the config file as well as the `parentField`.
- This does not support grandparents and grandchildren. The difficulty here is that to insert a grandchild document, we need the parent id (for `parent`) and the grandparent id (for `routing`). I propose we only support grandparent relationships when the grandchild documents contain a `parentField` and a `routingField`. This would avoid having to query the parent collection to find the parent's `_routing` to use for `routing` (what if the parent doesn't exist yet which may happen during the collection dump?). This would support great-grandchildren, great-great-grandchildren, etc. automatically. Extending the example below with the [Elasticsearch Grandparents example](https://www.elastic.co/guide/en/elasticsearch/guide/2.x/grandparents.html):
```json
{
  "mainAddress": "localhost:27017",
  "verbosity": 2,
  "docManagers":[
    {
      "docManager": "elastic2_doc_manager",
      "targetURL": "localhost:9200",
      "args": {
        "routing": {
          "company": {
            "branch": {
              "parentField": "country_id"
            },
            "employee": {
              "parentField": "branch_id",
              "routingField": "routing_id"
            }
          }
        }
      }
    }
  ]
}
```

2016-11-02 18:14 UTC, ShaneHarvey commented
@benan789 is this how you imagine grandparent relationships could work?

2016-11-02 19:06 UTC, benan789 commented
Yes, that's perfect.

2016-11-03 18:11 UTC, llvtt requested changes

2016-11-03 18:11 UTC, llvtt commented on mongo_connector/doc_managers/elastic2_doc_manager.py
> +            parent_args['parent'] = parent_id
This seems to be a common pattern:

```
parent_id = self._get_parent_id_from_mongodb(...)
parent_args = {}
if parent_id is not None:
    parent_args['parent'] = parent_id
```
perhaps this could be its own helper function? like:

    parent_args = self._get_parent_args(index, doc_type, doc)

2016-11-03 18:11 UTC, llvtt commented on mongo_connector/doc_managers/elastic2_doc_manager.py
> +            document = self._search_doc_by_id(index, doc_type, document_id)
Maybe this is something the BulkBuffer can help us with, once that gets merged in.

2016-11-14 19:25 UTC, benan789 commented
Is there an ETA on this? Thanks!

2016-11-21 08:15 UTC, StefanBalea commented
Will this feature be merged? Thanks!

2016-11-28 23:58 UTC, lnader commented
@ShaneHarvey - Sorry for the delay!  We were able to test this and it worked.

2016-11-29 03:38 UTC, marcuscarr commented
@ShaneHarvey - I've been testing this out for the use case my coworker @lnader asked about. It's working great! 👍

2016-12-17 02:20 UTC, aarestu commented
so, can I use this? and is this safe to use?
thank's masters 👍

2016-12-17 03:26 UTC, lnader commented
@ShaneHarvey - When will this get merged?  Thanks

2017-02-09 09:51 UTC, yomansk8 commented
Hello, any news on when we got this merged and we can use it ? Thanks!

2017-03-10 15:04 UTC, StefanBalea commented
Hello, any news on when we got this merged ? Thanks! :)

2017-03-31 21:01 UTC, lnader commented
When is this going to get merged?

2017-05-23 22:18 UTC, dblado commented
I'd like to use this too. Any update on when it will be merged?

2017-05-26 21:06 UTC, dblado commented on mongo_connector/doc_managers/elastic2_doc_manager.py
> +        return self._formatter.transform_value(doc.pop(parent_field, None))
I actually don't think the parent field should be popped off the doc. I use the parent field in queries as a filter. I can't find anything that speaks to the performance of has_parent, but my gut says that a bool.filter.term.paren_field="value" is more performant that has_parent.

2017-07-19 08:00 UTC, nVitius commented
Having this functionality would be super-helpful. @ShaneHarvey: any chance you could update this PR so we could look at merging it again?

2017-08-09 08:57 UTC, sorhent commented
Hello,
I performed some ugly development in order for mongo-connector to support parent/child relationship,
routing and to fit also with oplog issue: https://github.com/mongodb-labs/mongo-connector/issues/446
I could make a PR with the code as it is actually and if you want, you could improve it.
It works for me.

2017-09-19 09:21 UTC, eric-chao commented
I tested this case under es5.5.2,  not passed. :-(

2017-09-19 17:06:42,881 [CRITICAL] mongo_connector.oplog_manager:670 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 625, in do_dump
    upsert_all(dm)
  File "/usr/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 611, in upsert_all
    mapped_ns, long_ts)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 46, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 367, in bulk_upsert
    for ok, resp in responses:
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 163, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 135, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
OperationFailed: (u'3 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'employee', u'_id': u'59c0d72823ad98799d437c25', u'error': {u'index_uuid': u'_na_', u'index': u'company', u'reason': u'routing is required for [company]/[employee]/[59c0d72823ad98799d437c25]', u'type': u'routing_missing_exception'}, u'_index': u'company'}}, {u'index': {u'status': 400, u'_type': u'employee', u'_id': u'59c0d72823ad98799d437c27', u'error': {u'index_uuid': u'_na_', u'index': u'company', u'reason': u'routing is required for [company]/[employee]/[59c0d72823ad98799d437c27]', u'type': u'routing_missing_exception'}, u'_index': u'company'}}, {u'index': {u'status': 400, u'_type': u'employee', u'_id': u'59c0d72823ad98799d437c29', u'error': {u'index_uuid': u'_na_', u'index': u'company', u'reason': u'routing is required for [company]/[employee]/[59c0d72823ad98799d437c29]', u'type': u'routing_missing_exception'}, u'_index': u'company'}}])
2017-09-19 17:06:42,883 [ERROR] mongo_connector.oplog_manager:678 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(host=[u'localhost:27018'], document_class=dict, tz_aware=False, connect=True, replicaset=u'rs'), u'local'), u'oplog.rs')
2017-09-19 17:06:43,444 [ERROR] mongo_connector.connector:398 - MongoConnector: OplogThread <OplogThread(Thread-3, started 140243465701120)> unexpectedly stopped! Shutting down
2017-09-19 17:06:43,445 [INFO] mongo_connector.connector:459 - MongoConnector: Stopping all OplogThreads

2017-10-26 15:02 UTC, bartlettpsj commented
Please add me to the list of folk asking when this will be merged.  I need to link two huge collections and application side joins and nesting are out of the question.

2018-04-24 12:17 UTC, songguohfut commented
hello~when will it be merged?

2018-06-29 03:14 UTC, ft0907 commented
@eric-chao I have a similar problem. How did you solve it? Or is this branch not integrated into the main molecule, which is unable to use this function? 
@ShaneHarvey 
Does the current version have been supportedParent-child relationship Or does it support mongodb DBref?

2018-11-04 09:06 UTC, jaraco commented
Sadly, this PR has some non-trivial merge conflicts with the implementation. @ShaneHarvey if you're willing to resolve the merge conflicts and if you don't think the implementation is stable enough for a release, I'd like to get it out, as it sounds like there's some good demand for it.

2019-09-09 23:21 UTC, ShaneHarvey commented
I'm cleaning up some old issues highlighted by the new github dashboard UI and realized this is still open. Sorry for the huge delay here @jaraco (and everyone else waiting for this feature).

The problem with this PR is that it conflicts with the bulk/buffering work added in  https://github.com/yougov/elastic2-doc-manager/pull/15. Resolving the conflicts are definitely non-trivial. In order for this to be merged I think the buffering logic might need to be simplified to make parent-child lookup logic simpler. That said, I haven't worked on this project for quite a while and my knowledge of Elastic is also not up to date so there might be a solution that does not involve changing the bulk buffer logic.

For now I'm going to close this PR because I'm not planning to work on it. Anyone else is free to take over this work and open a new PR using the same ideas (as I did with #3).

2019-09-09 23:21 UTC, closed without merging